# generated by datamodel-codegen:
#   filename:  swagger.yaml
#   timestamp: 2023-09-11T13:51:27+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class DataType(Enum):
    STRING = 'STRING'
    INTEGER_64_BIT = 'INTEGER_64_BIT'
    DECIMAL_64_BIT = 'DECIMAL_64_BIT'
    BOOLEAN = 'BOOLEAN'
    TIMESTAMP = 'TIMESTAMP'


class Item(BaseModel):
    dataTableId: Optional[str] = Field(
        None, example='8787a1a4-0d3d-4cb7-88be-a689f5b6db3e'
    )
    dataId: Optional[str] = Field(None, example='22dad734-6fb5-41e8-b9ab-5ae7ad92a72e')
    attributeDataValues: Optional[Any] = None
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to data row resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/data/97ba50b4-bf77-11ed-afa1-0242ac120002',
    )


class QueryCompositeFilterType(Enum):
    AND = 'AND'
    OR = 'OR'
    NONE = 'NONE'


class QueryPropertyFilterType(Enum):
    EQUAL = 'EQUAL'
    NOT_EQUAL = 'NOT_EQUAL'
    LESS_THAN = 'LESS_THAN'
    LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL'
    GREATER_THAN = 'GREATER_THAN'
    GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL'
    IN = 'IN'
    NOT_IN = 'NOT_IN'
    NONE = 'NONE'


class OrderBySortType(Enum):
    ASCENDING = 'ASCENDING'
    DESCENDING = 'DESCENDING'
    NONE = 'NONE'


class Paging(BaseModel):
    pageLimit: Optional[int] = Field(
        None,
        description='The pageLimit used, the pageLimit may be smaller than requested because of a system imposed limit.',
        example=75,
    )
    next: Optional[AnyUrl] = Field(
        None,
        description='The system-generated URI to retrieve the next page of items',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/data?pageCursor=AQEADvF_74uzm_RspRkCJ4dfurDAnrRVAF6rzS4Rln8tLwlkNqnsV-Wi8TXYSsMHGis8&pageLimit=75',
    )


class DomainRef(BaseModel):
    domainId: Optional[str] = Field(
        None, description='The domain identifier.', example='87000000001079'
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to the domain resource.',
        example='https://api.prod.us.five9.net/domains/v1/domains/87000000001079',
    )


class AttributeRef(BaseModel):
    attributeId: str = Field(
        ...,
        description='The Attribute identifier.',
        example='97ba50b4-bf77-11ed-afa1-0242ac120002',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to the Attribute resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/attributes/97ba50b4-bf77-11ed-afa1-0242ac120002',
    )


class QueryRef(BaseModel):
    queryId: str = Field(
        ...,
        description='The QueryCompositeFilter identifier.',
        example='97ba50b4-bf77-11ed-afa1-0242ac120002',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to the QueryCompositeFilter resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/queries/97ba50b4-bf77-11ed-afa1-0242ac120002',
    )


class QueryCompositeFilterRef(BaseModel):
    queryCompositeFilterRefId: str = Field(
        ...,
        description='The QueryCompositeFilter identifier.',
        example='97ba50b4-bf77-11ed-afa1-0242ac120002',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to the QueryCompositeFilter resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/queries/97ba50b4-bf77-11ed-afa1-0242ac120002/query-composite-filters/57f2f232-e2b9-11ed-b5ea-0242ac120002',
    )


class QueryPropertyFilterRef(BaseModel):
    queryPropertyFilterRefId: str = Field(
        ...,
        description='The QueryPropertyFilter identifier.',
        example='50029e42-f8b2-11ed-be56-0242ac120002',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to the QueryPropertyFilter resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/queries/97ba50b4-bf77-11ed-afa1-0242ac120002/query-composite-filters/57f2f232-e2b9-11ed-b5ea-0242ac120002/query-property-filters/50029e42-f8b2-11ed-be56-0242ac120002',
    )


class HttpErrorDetail(BaseModel):
    code: str = Field(..., description='Error code associated to the error detail.')
    message: str = Field(
        ..., description='Error message associated to the error detail.'
    )
    path: Optional[str] = Field(
        None,
        description='Path to the path paremeter, query parameter, request object or attribute that caused this error detail.',
    )
    invalidValue: Optional[str] = Field(
        None, description='The value of the item that caused the error.'
    )


class DataTable(BaseModel):
    domain: Optional[DomainRef] = None
    dataTableId: Optional[str] = Field(
        None, example='22dad734-6fb5-41e8-b9ab-5ae7ad92a72e'
    )
    dataTableName: constr(pattern=r'^[A-Z_]+$') = Field(..., example='DATA_TABLE_NAME')
    dataTableDescription: Optional[str] = Field(
        None, example='A user supplied description describing this data table.'
    )
    createdOn: Optional[datetime] = None
    lastModifiedOn: Optional[datetime] = None
    rowCount: Optional[int] = Field(None, example=5)
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to data table resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e',
    )


class DataTables(BaseModel):
    domain: Optional[DomainRef] = None
    items: Optional[List[DataTable]] = None
    paging: Optional[Paging] = None


class Attribute(BaseModel):
    domain: Optional[DomainRef] = None
    dataTableId: Optional[str] = Field(
        None, example='22dad734-6fb5-41e8-b9ab-5ae7ad92a72e'
    )
    attributeId: Optional[str] = Field(
        None, example='97ba50b4-bf77-11ed-afa1-0242ac120002'
    )
    attributeName: str = Field(..., example='COLUMN_A')
    attributeDefaultValue: Optional[str] = Field(None, example='500')
    attributeMinimumValue: Optional[str] = Field(None, example='0')
    attributeMaximumValue: Optional[str] = Field(None, example='1000')
    unique: Optional[bool] = Field(
        None,
        description='If true this attribute is unique. An error on data insert will be thrown if a duplicate data value already exists for this attribute.',
        example=False,
    )
    required: Optional[bool] = Field(
        None,
        description='If true this attribute will be required to have a non-null value when creating a row in a data table.',
        example=False,
    )
    containsSensitiveData: Optional[bool] = Field(
        None,
        description='A flag that indicates of this attribute contains sensitive data.',
        example=False,
    )
    dataType: DataType = Field(..., example='INTEGER_64_BIT')
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to attribute resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/attributes/97ba50b4-bf77-11ed-afa1-0242ac120002',
    )


class DataRow(BaseModel):
    domain: Optional[DomainRef] = None
    dataTableId: Optional[str] = Field(
        None, example='8787a1a4-0d3d-4cb7-88be-a689f5b6db3e'
    )
    dataId: Optional[str] = Field(None, example='22dad734-6fb5-41e8-b9ab-5ae7ad92a72e')
    attributeDataValues: Optional[Any] = None
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to data row resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/data/97ba50b4-bf77-11ed-afa1-0242ac120002',
    )


class DataRows(BaseModel):
    domain: Optional[DomainRef] = None
    items: Optional[List[Item]] = None
    paging: Optional[Paging] = None


class QueryPropertyFilter(BaseModel):
    domain: Optional[DomainRef] = None
    dataTableId: Optional[str] = Field(
        None, example='8787a1a4-0d3d-4cb7-88be-a689f5b6db3e'
    )
    queryId: Optional[str] = Field(None, example='97ba50b4-bf77-11ed-afa1-0242ac120002')
    queryCompositeFilterId: Optional[str] = Field(
        None, example='57f2f232-e2b9-11ed-b5ea-0242ac120002'
    )
    queryPropertyFilterId: Optional[str] = Field(
        None, example='57f2f232-e2b9-11ed-b5ea-0242ac120002'
    )
    attributeId: str = Field(..., example='97ba50b4-bf77-11ed-afa1-0242ac120002')
    attributeName: Optional[str] = Field(
        None,
        description="The name of the attribute. This name will also be used as the 'key' for query parameter mapping.",
        example='attributeName3',
    )
    defaultAttributeValues: Optional[List] = Field(
        None,
        description="The default value to be used if no query param is provided along side the operator. Must match the attribute's data type.",
    )
    queryPropertyFilterType: QueryPropertyFilterType = Field(..., example='EQUAL')
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to QueryPropertyFilter row resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/queries/97ba50b4-bf77-11ed-afa1-0242ac120002/query-composite-filter/57f2f232-e2b9-11ed-b5ea-0242ac120002/query-proprety-filter/3fb26146-89ef-4b2d-8482-43feeef49193',
    )


class Query(BaseModel):
    domain: Optional[DomainRef] = None
    queryId: Optional[str] = Field(None, example='22dad734-6fb5-41e8-b9ab-5ae7ad92a72e')
    dataTableId: Optional[str] = Field(
        None, example='22dad734-6fb5-41e8-b9ab-5ae7ad92a72e'
    )
    queryName: str = Field(..., example='Name of the Query')
    queryDescription: Optional[str] = Field(
        None, example='A description by the user describing the query.'
    )
    queryCompositeFilter: Optional[QueryCompositeFilterRef] = None
    orderByAttribute: Optional[AttributeRef] = None
    targetAttributes: Optional[List[AttributeRef]] = None
    orderBySortType: Optional[OrderBySortType] = Field(None, example='DESCENDING')
    rowLimit: Optional[int] = Field(None, example=5)
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to query resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/queries/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e',
    )


class Queries(BaseModel):
    domain: Optional[DomainRef] = None
    items: Optional[List[QueryRef]] = None
    paging: Optional[Paging] = None


class QueryPropertyFilters(BaseModel):
    domain: Optional[DomainRef] = None
    items: Optional[List[QueryPropertyFilterRef]] = None
    paging: Optional[Paging] = None


class HttpError(BaseModel):
    traceId: str = Field(
        ...,
        description='A tracing identifier to allow the message as received by a client to be correlated with the error messages on the server.',
    )
    details: Optional[List[HttpErrorDetail]] = Field(
        None, description='Additional details that indicates the cause of the error.'
    )


class Attributes(BaseModel):
    domain: Optional[DomainRef] = None
    items: Optional[List[Attribute]] = None
    paging: Optional[Paging] = None


class QueryCompositeFilter(BaseModel):
    domain: Optional[DomainRef] = None
    dataTableId: Optional[str] = Field(
        None, example='8787a1a4-0d3d-4cb7-88be-a689f5b6db3e'
    )
    queryId: Optional[str] = Field(None, example='97ba50b4-bf77-11ed-afa1-0242ac120002')
    queryCompositeFilterId: Optional[str] = Field(
        None, example='57f2f232-e2b9-11ed-b5ea-0242ac120002'
    )
    parentQueryCompositeFilter: Optional[QueryCompositeFilterRef] = None
    queryCompositeFilterType: QueryCompositeFilterType = Field(..., example='AND')
    propertyFilters: Optional[List[QueryPropertyFilter]] = None
    childCompositeFilters: Optional[List[QueryCompositeFilter]] = None
    uri: Optional[AnyUrl] = Field(
        None,
        description='The URI to QueryCompositeFilter resource.',
        example='https://api.prod.us.five9.net/data-tables/v1/domains/87000000001079/data-tables/22dad734-6fb5-41e8-b9ab-5ae7ad92a72e/queries/97ba50b4-bf77-11ed-afa1-0242ac120002/query-composite-filter/57f2f232-e2b9-11ed-b5ea-0242ac120002',
    )


QueryCompositeFilter.model_rebuild()
